version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: playground

  zookeeper:
    image: debezium/zookeeper:2.1.3.Final
    restart: always
    ports:
      - '2181:2181'
    volumes:
      - zookeeper_data:/zookeeper/data
      - zookeeper_txns:/zookeeper/txns
      - zookeeper_logs:/zookeeper/logs
      - zookeeper_conf:/zookeeper/conf
      - zookeeper_tmp:/tmp

  kafka:
    image: debezium/kafka:2.1.3.Final
    restart: always
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    volumes:
      - kafka_data:/kafka/data
      - kafka_logs:/kafka/logs
      - kafka_config:/kafka/config
    environment:
      BROKER_ID: 1
      ZOOKEEPER_CONNECT: 'zookeeper:2181'

volumes:
  postgres:
  zookeeper_data:
  zookeeper_txns:
  zookeeper_logs:
  zookeeper_conf:
  zookeeper_tmp:
  kafka_data:
  kafka_logs:
  kafka_config: